services:
  ##############
  # AES
  ##############
  aes-go:
    image: vhiveease/aes-go:latest
    container_name: aes-go
    cpuset: "1"
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50051
    ports:
      - target: 50051
  relay_aes-go:
    image: vhiveease/relay:latest
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50000
      - --function-endpoint-url=aes-go
      - --function-endpoint-port=50051
      - --function-name=aes-go
    ports:
      - published: 50000
        target: 50000

  aes-nodejs:
    image: vhiveease/aes-nodejs:latest
    container_name: aes-nodejs
    cpuset: "1"
    entrypoint:
      - node
      - server.js
      - --addr=0.0.0.0
      - --port=50051
    ports:
      - target: 50051
  relay_aes-nodejs:
    image: vhiveease/relay:latest
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50001
      - --function-endpoint-url=aes-nodejs
      - --function-endpoint-port=50051
      - --function-name=aes-nodejs
    ports:
        - published: 50001
          target: 50001

  aes-python:
    image: vhiveease/aes-python:latest
    container_name: aes-python
    cpuset: "1"
    entrypoint:
      - python
      - /app/server.py
      - --addr=0.0.0.0
      - --port=50051
    ports:
      - target: 50051
  relay_aes-python:
    image: vhiveease/relay:latest
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50002
      - --function-endpoint-url=aes-python
      - --function-endpoint-port=50051
      - --function-name=aes-python
    ports:
        - published: 50002
          target: 50002
  ##############
  # AUTH
  ##############
  auth-go:
    image: vhiveease/auth-go:latest
    container_name: auth-go
    cpuset: "1"
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50051
    ports:
      - target: 50051
  relay_auth-go:
    image: vhiveease/relay:latest
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50003
      - --function-endpoint-url=auth-go
      - --function-endpoint-port=50051
      - --function-name=auth-go
    ports:
      - published: 50003
        target: 50003

  auth-nodejs:
    image: vhiveease/auth-nodejs:latest
    container_name: auth-nodejs
    cpuset: "1"
    entrypoint:
      - node
      - server.js
      - --addr=0.0.0.0
      - --port=50051
    ports:
      - target: 50051
  relay_auth-nodejs:
    image: vhiveease/relay:latest
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50004
      - --function-endpoint-url=auth-nodejs
      - --function-endpoint-port=50051
      - --function-name=auth-nodejs
    ports:
        - published: 50004
          target: 50004

  auth-python:
    image: vhiveease/auth-python:latest
    container_name: auth-python
    cpuset: "1"
    entrypoint:
      - python
      - /app/server.py
      - --addr=0.0.0.0
      - --port=50051
    ports:
      - target: 50051
  relay_auth-python:
    image: vhiveease/relay:latest
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50005
      - --function-endpoint-url=auth-python
      - --function-endpoint-port=50051
      - --function-name=auth-python
    ports:
        - published: 50005
          target: 50005

  ##############
  # FIB
  ##############
  fibonacci-go:
    image: vhiveease/fibonacci-go:latest
    container_name: fibonacci-go
    cpuset: "1"
    entrypoint:
      - /app/server
      - -addr=0.0.0.0:50051
    ports:
      - target: 50051
  relay_fib-go:
    image: vhiveease/relay:latest
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50006
      - --function-endpoint-url=fibonacci-go
      - --function-endpoint-port=50051
      - --function-name=fibonacci-go
      - --value=10
      - --generator=linear
      - --lowerBound=1
      - --upperBound=10
    ports:
      - published: 50006
        target: 50006

  fibonacci-nodejs:
    image: vhiveease/fibonacci-nodejs:latest
    container_name: fibonacci-nodejs
    cpuset: "1"
    entrypoint:
      - node
      - server.js
      - --addr=0.0.0.0
      - --port=50051
    ports:
      - target: 50051

  relay_fib-nodejs:
    image: vhiveease/relay:latest
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50007
      - --function-endpoint-url=fibonacci-nodejs
      - --function-endpoint-port=50051
      - --function-name=fibonacci-nodejs
      - --value=10
      - --generator=linear
      - --lowerBound=1
      - --upperBound=10
    ports:
        - published: 50007
          target: 50007

  fibonacci-python:
    image: vhiveease/fibonacci-python:latest
    container_name: fibonacci-python
    cpuset: "1"
    entrypoint:
      - python
      - /app/server.py
      - --addr=0.0.0.0
      - --port=50051
    ports:
      - target: 50051
  relay_fib-python:
    image: vhiveease/relay:latest
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50008
      - --function-endpoint-url=fibonacci-python
      - --function-endpoint-port=50051
      - --function-name=fibonacci-python
      - --value=10
      - --generator=linear
      - --lowerBound=1
      - --upperBound=10
    ports:
        - published: 50008
          target: 50008

  ##############
  # HOTEL-APP
  ##############
  geo:
    image: vhiveease/hotel-app-geo:latest
    container_name: geo
    cpuset: "1"
    entrypoint:
      - /app/server
      - --url=0.0.0.0
      - --port=8083
      - --db_addr=database_geo:5432
    ports:
      - target: 8083
    depends_on:
      - database_geo
  database_geo:
    image: vhiveease/postgres
    container_name: geo-db
    cpuset: "2"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hotel_geo
  relay_geo:
    image: vhiveease/relay:latest
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50009
      - --function-endpoint-url=geo
      - --function-endpoint-port=8083
      - --function-name=geo
    ports:
      - published: 50009
        target: 50009
    depends_on:
      - geo

  profile:
    image: vhiveease/hotel-app-profile:latest
    container_name: profile
    cpuset: "1"
    entrypoint:
      - /app/server
      - --url=0.0.0.0
      - --port=8083
      - --db_addr=database_profile:5432
      - --memcached_addr=memcached_profile:11211
    ports:
      - target: 8083
    depends_on:
      - database_profile
      - memcached_profile
  database_profile:
    image: vhiveease/postgres
    container_name: profile-db
    cpuset: "2"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hotel_profile
  memcached_profile:
    image: vhiveease/memcached
    container_name: 'profile-mmc'
    cpuset: "2"
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_THREADS=2
    logging:
      options:
        max-size: 50m
  relay_profile:
    image: vhiveease/relay:latest
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50010
      - --function-endpoint-url=profile
      - --function-endpoint-port=8083
      - --function-name=profile
      - --value="2,12,21"
    ports:
      - published: 50010
        target: 50010
    depends_on:
      - profile

  rate:
    image: vhiveease/hotel-app-rate:latest
    container_name: rate
    cpuset: "1"
    entrypoint:
      - /app/server
      - --url=0.0.0.0
      - --port=8083
      - --db_addr=database_rate:5432
      - --memcached_addr=memcached_rate:11211
    ports:
      - target: 8083
    depends_on:
      - database_rate
      - memcached_rate
  database_rate:
    image: vhiveease/postgres
    container_name: rate-db
    cpuset: "2"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hotel_rate
  memcached_rate:
    image: vhiveease/memcached
    container_name: 'rate-mmc'
    cpuset: "2"
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_THREADS=2
    logging:
      options:
        max-size: 50m
  relay_rate:
    image: vhiveease/relay:latest
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50011
      - --function-endpoint-url=rate
      - --function-endpoint-port=8083
      - --function-name=rate
      - --value=1
    ports:
      - published: 50011
        target: 50011
    depends_on:
      - rate

  recommendation:
    image: vhiveease/hotel-app-recommendation:latest
    container_name: recommendation
    cpuset: "1"
    entrypoint:
      - /app/server
      - --url=0.0.0.0
      - --port=8083
      - --db_addr=database_recommendation:5432
    ports:
      - target: 8083
    depends_on:
      - database_recommendation
  database_recommendation:
    image: vhiveease/postgres
    container_name: recommendation-db
    cpuset: "2"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hotel_recommendation
  relay_recommendation:
    image: vhiveease/relay:latest
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50012
      - --function-endpoint-url=recommendation
      - --function-endpoint-port=8083
      - --function-name=recommendation
      - --value="dis"
    ports:
      - published: 50012
        target: 50012
    depends_on:
      - recommendation

  reservation:
    image: vhiveease/hotel-app-reservation:latest
    container_name: reservation
    cpuset: "1"
    entrypoint:
      - /app/server
      - --url=0.0.0.0
      - --port=8083
      - --db_addr=database_reservation:5432
      - --memcached_addr=memcached_reservation:11211
    ports:
      - target: 8083
    depends_on:
      - database_reservation
      - memcached_reservation
  database_reservation:
    image: vhiveease/postgres
    container_name: reservation-db
    cpuset: "2"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hotel_reservation
  memcached_reservation:
    image: vhiveease/memcached
    container_name: 'reservation-mmc'
    cpuset: "2"
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_THREADS=2
    logging:
      options:
        max-size: 50m
  relay_reservation:
    image: vhiveease/relay:latest
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50013
      - --function-endpoint-url=reservation
      - --function-endpoint-port=8083
      - --function-name=reservation
      - --function-method=CheckAvailability
    ports:
      - published: 50013
        target: 50013
    depends_on:
      - reservation

  user:
    image: vhiveease/hotel-app-user:latest
    container_name: user
    cpuset: "1"
    entrypoint:
      - /app/server
      - --url=0.0.0.0
      - --port=8083
      - --db_addr=database_user:5432
    ports:
      - target: 8083
    depends_on:
      - database_user
  database_user:
    image: vhiveease/postgres
    container_name: user-db
    cpuset: "2"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hotel_user
  relay_user:
    image: vhiveease/relay:latest
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50014
      - --function-endpoint-url=user
      - --function-endpoint-port=8083
      - --function-name=user
      - --value=hello
    ports:
      - published: 50014
        target: 50014
    depends_on:
      - user

  ##############
  # ONLINE-SHOP
  ##############
  currencyservice:
    image: vhiveease/onlineshop-currencyservice:latest
    container_name: 'currencyservice'
    cpuset: "1"
    environment:
      - PORT=7000
      - DISABLE_PROFILER=true
      - DISABLE_DEBUGGER=true
      - DISABLE_TRACING=true
    entrypoint: [ "node", "server.js" ]
    ports:
    - target: 7000
  relay_currencyservice:
    image: vhiveease/relay:latest
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50015
      - --function-endpoint-url=currencyservice
      - --function-endpoint-port=7000
      - --function-name=currencyservice
      - --generator=unique
      - --value=100
      - --function-method=Convert
    ports:
      - published: 50015
        target: 50015
    depends_on:
      - currencyservice

  emailservice:
    image: vhiveease/onlineshop-emailservice:latest
    container_name: 'emailservice'
    cpuset: "1"
    build:
      context: ./../../emailservice/
      dockerfile: ./Dockerfile
    environment:
      - DISABLE_PROFILER=true
      - DISABLE_DEBUGGER=true
      - DISABLE_TRACING=true
    ports:
    - target: 8080
  relay_emailservice:
    image: vhiveease/relay:latest
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50016
      - --function-endpoint-url=emailservice
      - --function-endpoint-port=8080
      - --function-name=emailservice
      - --generator=unique
    ports:
      - published: 50016
        target: 50016
    depends_on:
      - emailservice

  paymentservice:
    image: vhiveease/onlineshop-paymentservice:latest
    container_name: 'paymentservice'
    cpuset: "1"
    build:
      context: ./../../paymentservice/
      dockerfile: ./Dockerfile
    environment:
      - PORT=50051
      - DISABLE_PROFILER=true
      - DISABLE_DEBUGGER=true
      - DISABLE_TRACING=true
    ports:
    - target: 50051
  relay_paymentservice:
    image: vhiveease/relay:latest
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50017
      - --function-endpoint-url=paymentservice
      - --function-endpoint-port=50051
      - --function-name=paymentservice
      - --generator=unique
      - --value=100
    ports:
      - published: 50017
        target: 50017
    depends_on:
      - paymentservice

  productcatalogservice:
    image: vhiveease/onlineshop-productcatalogservice:latest
    container_name: 'productcatalogservice'
    cpuset: "1"
    environment:
      - PORT=3550
      - DISABLE_PROFILER=true
      - DISABLE_DEBUGGER=true
      - DISABLE_TRACING=true
    ports:
    - target: 3550
  relay_productcatalogservice:
    image: vhiveease/relay:latest
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50018
      - --function-endpoint-url=productcatalogservice
      - --function-endpoint-port=3550
      - --function-name=productcatalogservice
      - --generator=unique
      - --value=loremipsum
      - --function-method=ListProducts
    ports:
      - published: 50018
        target: 50018
    depends_on:
      - productcatalogservice

  shippingservice:
    image: vhiveease/onlineshop-shippingservice:latest
    container_name: 'shippingservice'
    cpuset: "1"
    environment:
      - PORT=3550
      - DISABLE_PROFILER=true
      - DISABLE_DEBUGGER=true
      - DISABLE_TRACING=true
    ports:
    - target: 3550
  relay_shippingservice:
    image: vhiveease/relay:latest
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50019
      - --function-endpoint-url=shippingservice
      - --function-endpoint-port=3550
      - --function-name=shippingservice
      - --generator=unique
      - --function-method=ShipOrder
    ports:
      - published: 50019
        target: 50019
    depends_on:
      - shippingservice

